### ISSUE TITLE
KeyError: 'keypoints2d_unproj' when 'python3 apps/demo/mocap py ./dataset/1v1p --work internet'

### ISSUE THREAD

**Issue by Miles629** [zju3dv/EasyMocap#225]
Thanks for your exciting work! 
I downloaded the sample data '1v1p', and then ran `python3 apps/demo/mocap py ./dataset/1v1p --work internet`
Then get the following error:
`(easymocap) root@sleep-everyday:~/EasyMocap# python3 apps/demo/mocap.py ./dataset/1v1p --work internet
[run] python3 apps/calibration/create_blank_camera.py ./dataset/1v1p
Read shape (1080, 1920, 3) from image ./dataset/1v1p/images/0+000553+000965/000000.jpg
Read shape (1080, 1918, 3) from image ./dataset/1v1p/images/2+002300+002900/000000.jpg
[run] python3 apps/fit/fit.py --cfg_model config/model/smpl.yml --cfg_data config/data/multivideo.yml --cfg_exp config/fit/1v1p.yml --opt_data "args.path" "./dataset/1v1p" "args.out" "./dataset/1v1p/output-smpl-3d" "args.camera" "./dataset/1v1p" --opt_exp "args.stages.joints.loss.k2d.weight" "100." "args.stages.joints.loss.k2d.args.norm" "gm"
Key is not in the template: args.out
[Info] Load 2 folders: 0+000553+000965 2+002300+002900...
[Info] Load [0, -1, 1] frames
-> [Loading config/data/multivideo.yml]:  21.1ms
-> [Loading config/model/smpl.yml]:   6.3s
Loading 0+000553+000965:   0%|                                                                    | 0/412 [00:00<?, ?it/s]
optimizing:   0%|                                                                                   | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/EasyMocap/apps/fit/fit.py", line 38, in <module>
    fitter.fit(body_model, dataset)
  File "/root/EasyMocap/easymocap/multistage/base.py", line 294, in fit
    for data in dataloader:
  File "/root/anaconda3/envs/easymocap/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/root/anaconda3/envs/easymocap/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/easymocap/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/anaconda3/envs/easymocap/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/easymocap/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/EasyMocap/easymocap/datasets/base.py", line 553, in __getitem__
    data = super().__getitem__(info['index'])
  File "/root/EasyMocap/easymocap/datasets/base.py", line 470, in __getitem__
    self.cache_shape[_key] = np.zeros_like(data[_key])
KeyError: 'keypoints2d_unproj'`
It seems the code can't find 'K' here:
`if K is not None:
      data[key] = Undistort.points(data[key], K, dist)
      data[key+'_unproj'] = unproj(data[key], invK)
for _key in [key, key+'_distort', key+'_unproj']:
      self.cache_shape[_key] = np.zeros_like(data[_key])`
how to deal with it? I want to get smpl poses, shapes and it's Rh, Th on a monocular video of one person.

**Comment by chingswy** [comment]
Can you paste the dataset ?

**Comment by Miles629** [comment]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/55200699/200153167-63ea07ea-3d10-4468-81eb-643fc995abc3.png">

I download the dataset from this [page](https://chingswy.github.io/easymocap-public-doc/quickstart/quickstart.html),
 I want to try the monocular video example and then use easymocap to estimate SMPL of my custom monocular video. 

In order to make your positioning easier, I paste the useful information here:
`Demo on monocular videos
Download demo dataset [here](https://zjueducn-my.sharepoint.com/:u:/g/personal/s_q_zju_edu_cn/ET-rr5vcXQ9DrORrmmRlOpgBttcEtdmL-tZAx5J124_jiw?e=tC96Mo) and extract the dataset.

data=<path/to/data>
python3 apps/demo/mocap.py ${data} --work internet`

I don't know what I did wrong, but the error seems to be  the code can't find 'K'. Looking forward to your reply~

**Comment by Trzeth** [comment]
Modify `easymocap/datasets/base.py` as follow will work 😄 @Miles629 
```python
Line 548 ...
            else:
                camera = read_cameras(self.root)[sub]
                K, dist = camera['K'], camera['dist']
                data = super().__getitem__(info['index'],K=K, dist=dist)
                for oldkey, newkey in [('K', 'K'), ('dist', 'dist'), ('R', 'Rc'), ('T', 'Tc')]:
                    data[newkey] = camera[oldkey].astype(np.float32)
...
```

**Comment by JACKYLUO1991** [comment]
@Miles629 I have the same problem... Have u solved it?

**Comment by Miles629** [comment]
> @Miles629 I have the same problem... Have u solved it?

Hi, @JACKYLUO1991 . @Trzeth commented 5 days ago to solve this problem. I'm too busy to try it, so I can't tell you whether it works or not. Logically, modifying code can solve this problem. Have you tried to modify the code like what @Trzeth commented?
Thank you for your comments @Trzeth  !

**Comment by JACKYLUO1991** [comment]
@Miles629 The code line numbers don't correspond, and I don't know where to change them? @Trzeth

**Comment by Trzeth** [comment]
@JACKYLUO1991 
There is a `else` statment at Line 549, maybe you should give it a try.
Also make sure it's easymocap/dataset`s`/base.py not easymocap/dataset/base.py, which is very similar. 😉

**Comment by siyuan-peng** [comment]
> @JACKYLUO1991 There is a `else` statment at Line 549, maybe you should give it a try. Also make sure it's easymocap/dataset`s`/base.py not easymocap/dataset/base.py, which is very similar. 😉

same problem here. I've done what you told and the error is still not resolved

**Comment by Trzeth** [comment]
@siyuan-peng Any error msg?

**Comment by Trzeth** [comment]
@siyuan-peng 
Could you check whether extri.yml and intri.yml under 1v1p folder?

**Comment by Trzeth** [comment]
@siyuan-peng 
The code above read extri.yml and intri.yml under 1v1p folder. It's a fixed camera args for whole video.
These two files generated by mocap.py everytime automatically.

Maybe the path of these two files is not correct, or it doesn't even generate properly by EasyMocap.
You have to check it by yourself.

May Python and EasyMocap God helps you.

**Comment by chingswy** [comment]
I'll check it.

**Comment by siyuan-peng** [comment]
> I'll check it.
Hello Qing, have you solved the issue?

**Comment by chingswy** [comment]
> > I'll check it.
> 
> Hello Qing, have you solved the issue?

I have checked the code and everything works well. Can you paste the full log?

**Comment by siyuan-peng** [comment]
> > > I'll check it.
> > 
> > 
> > Hello Qing, have you solved the issue?
> 
> I have checked the code and everything works well. Can you paste the full log?

It finally worked on WSL. I guess that it might be caused by the file path differences between windows and linux. Thanks for your quick reply!
