### ISSUE TITLE
Can't start demo: data/inputvideos/output-smpl-3d/smplmesh'

### ISSUE THREAD

**Issue by stpn** [zju3dv/EasyMocap#233]
Hi thanks a lot for this project. Trying to set it up on Ubuntu 20.04 
conda, pytorch and cuda are all installed, but I am still getting the `data/inputvideos/output-smpl-3d/smplmesh'` error

What could be the issue here?

thank you

```
python apps/demo/mocap.py ${data} --work internet
```

```
-> [Loading config/data/multivideo.yml]:  19.1ms
-> [Loading config/model/smpl.yml]:   6.6s
Loading 1223:   0%|                                                                                | 0/83 [00:00<?, ?it/s]
optimizing:   0%|                                                                                   | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/EasyMocap/apps/fit/fit.py", line 38, in <module>
    fitter.fit(body_model, dataset)
  File "/home/ubuntu/EasyMocap/easymocap/multistage/base.py", line 294, in fit
    for data in dataloader:
  File "/opt/conda/lib/python3.9/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/ubuntu/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ubuntu/.local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/.local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/EasyMocap/easymocap/datasets/base.py", line 550, in __getitem__
    data = super().__getitem__(info['index'])
  File "/home/ubuntu/EasyMocap/easymocap/datasets/base.py", line 409, in __getitem__
    data = super().__getitem__(index)
  File "/home/ubuntu/EasyMocap/easymocap/datasets/base.py", line 301, in __getitem__
    if not os.path.exists(annname) and not self.annot_args.read:
  File "/home/ubuntu/EasyMocap/easymocap/config/yacs.py", line 134, in __getattr__
    raise AttributeError(name)
AttributeError: read
Traceback (most recent call last):
  File "/home/ubuntu/EasyMocap/apps/demo/mocap.py", line 394, in <module>
    workflow(args.work, args)
  File "/home/ubuntu/EasyMocap/apps/demo/mocap.py", line 340, in workflow
    append_mocap_flags(path, output, cfg_data, cfg_model, cfg_exp, workflow.fit, args)
  File "/home/ubuntu/EasyMocap/apps/demo/mocap.py", line 277, in append_mocap_flags
    filenames = os.listdir(outdir)
FileNotFoundError: [Errno 2] No such file or directory: 'data/inputvideos/output-smpl-3d/smplmesh'
```

**Comment by stpn** [comment]
user error :)

**Comment by gsygsy96** [comment]
Hi @stpn , could you tell me how to solve this problem?

**Comment by stpn** [comment]
> Hi @stpn , could you tell me how to solve this problem?

sorry I don't remember exactly, it was something very basic, like a path or an environment issue.

**Comment by WinstonDeng** [comment]
@gsygsy96 Hi, have you solve it?

**Comment by tleyden** [comment]
@WinstonDeng I hit the same issue and solved it by creating the directory with `mkdir -p data/inputvideos/output-smpl-3d/smplmesh`.  (seems like a small bug in the script, it should lazily create this)

After you run `python apps/demo/mocap.py ${data} --work internet` it will create the files:

```
drwxrwxr-x 2   16K May 19 03:39 0+000553+000965
-rw-rw-r-- 1  1.1M May 19 03:43 0+000553+000965.mp4
drwxrwxr-x 2   20K May 19 03:43 2+002300+002900
-rw-rw-r-- 1  2.8M May 19 03:43 2+002300+002900.mp4
```
