### ISSUE TITLE
错误提示：RuntimeError: size of dimension does not match previous size, operand 1, dim 2

### ISSUE THREAD

**Issue by kongxm889** [zju3dv/EasyMocap#24]
运行 python apps/demo/mv1p.py E:\zju-ls-feng --out E:\zju-ls-feng\out  --vis_det --vis_repro --undis --sub_vis 1 7 13 19 --vis_smpl

**Comment by chingswy** [comment]
具体报错信息？

**Comment by kongxm889** [comment]
> 具体报错信息？

这个是具体报错信息
Traceback (most recent call last):
File "apps/demo/mv1p.py", line 109, in
mv1pmf_smpl(dataset, args)
File "apps/demo/mv1p.py", line 69, in mv1pmf_smpl
params = smpl_from_keypoints3d2d(body_model, kp3ds, keypoints2d, bboxes,
File "e:\easymocap\easymocap\pipeline\basic.py", line 49, in smpl_from_keypoints3d2d
params_shape = optimizeShape(body_model, params_init, kp3ds,
File "e:\easymocap\easymocap\pyfitting\optimize_simple.py", line 71, in optimizeShape
final_loss = fitting.run_fitting(optimizer, closure, opt_params)
File "e:\easymocap\easymocap\pyfitting\optimize.py", line 38, in run_fitting
loss = optimizer.step(closure)
File "e:\easymocap\easymocap\pyfitting\lbfgs.py", line 307, in step
orig_loss = closure()
File "e:\easymocap\easymocap\pyfitting\optimize_simple.py", line 46, in closure
keypoints3d = body_model(return_verts=False, return_tensor=True, only_shape=True, **body_params)
File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 532, in call
result = self.forward(*input, **kwargs)
File "e:\easymocap\easymocap\smplmodel\body_model.py", line 253, in forward
vertices, joints = lbs(shapes, poses, self.j_v_template,
File "e:\easymocap\easymocap\smplmodel\lbs.py", line 186, in lbs
v_shaped = v_template + blend_shapes(betas, shapedirs)
File "e:\easymocap\easymocap\smplmodel\lbs.py", line 273, in blend_shapes
blend_shape = torch.einsum('bl,mkl->bmk', [betas, shape_disps])
File "C:\ProgramData\Anaconda3\lib\site-packages\torch\functional.py", line 241, in einsum
return torch._C._VariableFunctions.einsum(equation, operands)
RuntimeError: size of dimension does not match previous size, operand 1, dim 2
PS E:\EasyMocap>

**Comment by kongxm889** [comment]
> I have updated the code, please retry.
Another problem has arisen
-> [Optimize global RT  ]: 1746.3ms
-> [Optimize 3D Pose/800 frames]: 15558.7ms
-> [Optimize 2D Pose/800 frames]:  49.4ms
Traceback (most recent call last):
  File "apps/demo/mv1p.py", line 109, in <module>
    mv1pmf_smpl(dataset, args)
  File "apps/demo/mv1p.py", line 69, in mv1pmf_smpl
    params = smpl_from_keypoints3d2d(body_model, kp3ds, keypoints2d, bboxes,
  File "e:\easymocap\easymocap\pipeline\basic.py", line 62, in smpl_from_keypoints3d2d
    params = multi_stage_optimize(body_model, params, kp3ds, kp2ds, bboxes, Pall, weight_pose, cfg)
  File "e:\easymocap\easymocap\pipeline\basic.py", line 37, in multi_stage_optimize
    params = optimizePose2D(body_model, params, bboxes, kp2ds, Pall, weight=weight, cfg=cfg)
  File "e:\easymocap\easymocap\pyfitting\optimize_simple.py", line 349, in optimizePose2D
    params = _optimizeSMPL(body_model, params, prepare_funcs, postprocess_funcs, loss_funcs, weight_loss=weight, cfg=cfg)
  File "e:\easymocap\easymocap\pyfitting\optimize_simple.py", line 246, in _optimizeSMPL
    final_loss = fitting.run_fitting(optimizer, closure, opt_params)
  File "e:\easymocap\easymocap\pyfitting\optimize.py", line 38, in run_fitting
    loss = optimizer.step(closure)
  File "e:\easymocap\easymocap\pyfitting\lbfgs.py", line 307, in step
    orig_loss = closure()
  File "e:\easymocap\easymocap\pyfitting\optimize_simple.py", line 231, in closure
    loss_dict = {key:func(kpts_est=kpts_est, **new_params) for key, func in loss_funcs.items()}
  File "e:\easymocap\easymocap\pyfitting\optimize_simple.py", line 231, in <dictcomp>
    loss_dict = {key:func(kpts_est=kpts_est, **new_params) for key, func in loss_funcs.items()}
  File "e:\easymocap\easymocap\pyfitting\lossfactory.py", line 321, in __call__
    kpts_homo = torch.cat([kpts_est[..., :self.nJoints, :], self.kpt_homo], dim=2)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 2. Got 25 and 118 in dimension 1 at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensor.cpp:612

**Comment by kongxm889** [comment]
> 我无法重现此命令，您使用的命令是什么？请添加标志`--verbose `并粘贴完整的输出。



> 我已更新代码，请重试。

Thank you. The problem has been solved

**Comment by kongxm889** [comment]
> I have updated the code, please retry.

Thank you. The problem has been solved
