### ISSUE TITLE
KeyError: 'nJoints' when running quickstart example

### ISSUE THREAD

**Issue by canghaiyunfan** [zju3dv/EasyMocap#250]
when I run the example code, get error as follows:
```python3 apps/demo/mv1p.py ./zju-ls-feng --out ./zju-ls-feng/output/manor --vis_det --vis_repro --undis --sub_vis 1 7 13 19 --body handr --model manor --gender male --vis_smpl```

 Demo code for multiple views and one person:

    - Input : /data/code/EasyMocap/zju-ls-feng => 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23
    - Output: /data/code/EasyMocap/zju-ls-feng/output/manol
    - Body  : manol=>male, handl

triangulation:   0%|                                                                                                                                                | 0/800 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/code/EasyMocap/apps/demo/mv1p.py", line 116, in <module>
    mv1pmf_skel(dataset, check_repro=True, args=args)
  File "/data/code/EasyMocap/apps/demo/mv1p.py", line 43, in mv1pmf_skel
    dataset.vis_detections(images, annots, nf, sub_vis=args.sub_vis)
  File "/data/code/EasyMocap/easymocap/dataset/mv1pmf.py", line 58, in vis_detections
    return super().vis_detections(images, lDetections, nf, sub_vis=sub_vis)
  File "/data/code/EasyMocap/easymocap/dataset/base.py", line 515, in vis_detections
    return self.writer.vis_keypoints2d_mv(images, lDetections, outname=outname, vis_id=True)
  File "/data/code/EasyMocap/easymocap/mytools/writer.py", line 51, in vis_keypoints2d_mv
    plot_keypoints(img, keypoints, pid=pid, config=self.config, use_limb_color=False, lw=2)
  File "/data/code/EasyMocap/easymocap/mytools/vis_base.py", line 138, in plot_keypoints
    for i in range(min(len(points), config['nJoints'])):
KeyError: 'nJoints'

**Comment by stevechaw** [comment]
Did you solve this?

**Comment by chingswy** [comment]
Please try the [v0.3](https://chingswy.github.io/easymocap-public-doc/develop/01_triangulate.html)
