### ISSUE TITLE
triangulation error says value error

### ISSUE THREAD

**Issue by josephajtaX** [zju3dv/EasyMocap#251]
Traceback (most recent call last):
  File "C:\easymocap\apps\demo\mv1p.py", line 116, in <module>
    mv1pmf_skel(dataset, check_repro=True, args=args)
  File "C:\easymocap\apps\demo\mv1p.py", line 43, in mv1pmf_skel
    dataset.vis_detections(images, annots, nf, sub_vis=args.sub_vis)
  File "c:\easymocap\easymocap\dataset\mv1pmf.py", line 58, in vis_detections
    return super().vis_detections(images, lDetections, nf, sub_vis=sub_vis)
  File "c:\easymocap\easymocap\dataset\base.py", line 512, in vis_detections
    valid_idx = [self.cams.index(i) for i in sub_vis]
  File "c:\easymocap\easymocap\dataset\base.py", line 512, in <listcomp>
    valid_idx = [self.cams.index(i) for i in sub_vis]
ValueError: '1' is not in list

i get this error when i enter this code to triangulate python apps/demo/mv1p.py 0_input/project --out 1_output/project --vis_det --vis_repro --undis --sub_vis 1 2 3 4 --vis_smpl

**Comment by chingswy** [comment]
Please try the [v0.3 code](https://chingswy.github.io/easymocap-public-doc/develop/01_triangulate.html)
