### ISSUE TITLE
No such file or directory: 'mirror-youtube-clip-videoonly/images

### ISSUE THREAD

**Issue by Reza-Noei** [zju3dv/EasyMocap#252]
Hi, 
I'm trying to run quick start samples (`mirror-youtube-clip-videoonly`). It took me about 3 days to resolve runtime errors. Until I stopped in following error. I had no more idea to correct it: 

```
[run] python3 apps/preprocess/extract_image.py /content/mirror-youtube-clip-videoonly
[run] python3 apps/calibration/create_blank_camera.py /content/mirror-youtube-clip-videoonly
Traceback (most recent call last):
  File "/content/EasyMocap/apps/calibration/create_blank_camera.py", line 24, in <module>
    subs = sorted(os.listdir(join(args.path, 'images')))
FileNotFoundError: [Errno 2] No such file or directory: '/content/mirror-youtube-clip-videoonly/images'
[Config] merge from parent file: config/data/multivideo.yml
[run] python3 apps/fit/fit.py --cfg_model config/model/smpl.yml --cfg_data config/data/multivideo-mirror.yml --cfg_exp config/fit/1v1p-mirror-direct.yml --opt_data "args.path" "/content/mirror-youtube-clip-videoonly" "args.out" "/content/mirror-youtube-clip-videoonly/output-smpl-3d" "args.camera" "/content/mirror-youtube-clip-videoonly" "args.writer.render.scale" "0.5"
[Config] merge from parent file: config/data/multivideo.yml
Key is not in the template: args.out
-> [Loading config/data/multivideo-mirror.yml]:  25.9ms
Traceback (most recent call last):
  File "/content/EasyMocap/apps/fit/fit.py", line 33, in <module>
    dataset = load_object(cfg_data.module, cfg_data.args)
  File "/content/EasyMocap/easymocap/config/baseconfig.py", line 67, in load_object
    obj = getattr(module, name)(**extra_args, **module_args)
  File "/content/EasyMocap/easymocap/datasets/base.py", line 511, in __init__
    super().__init__(**kwargs)
  File "/content/EasyMocap/easymocap/datasets/base.py", line 399, in __init__
    super().__init__(**kwargs)
  File "/content/EasyMocap/easymocap/datasets/base.py", line 222, in __init__
    self.subs = self.check_subs(path, subs)
  File "/content/EasyMocap/easymocap/datasets/base.py", line 256, in check_subs
    subs = sorted(os.listdir(join(path, self.image_args['root'])))
FileNotFoundError: [Errno 2] No such file or directory: '/content/mirror-youtube-clip-videoonly/images'
Traceback (most recent call last):
  File "/content/EasyMocap/apps/demo/mocap.py", line 394, in <module>
    workflow(args.work, args)
  File "/content/EasyMocap/apps/demo/mocap.py", line 340, in workflow
    append_mocap_flags(path, output, cfg_data, cfg_model, cfg_exp, workflow.fit, args)
  File "/content/EasyMocap/apps/demo/mocap.py", line 277, in append_mocap_flags
    filenames = os.listdir(outdir)
FileNotFoundError: [Errno 2] No such file or directory: '/content/mirror-youtube-clip-videoonly/output-smpl-3d/smplmesh'
```

My runtime environment is a google colab notebook, because I had several problems with `Pickle` in my ubuntu which leads me to *.pkl file loading issue. I will open up another issue about the `pickle` error.

Please help me on this 😢
I supposed that it takes me some hours but my manager is angry by now (he is waiting for my results 🤦‍♂️).

tnx

**Comment by chingswy** [comment]
Hello, can you check the path `/content/mirror-youtube-clip-videoonly`?

**Comment by Reza-Noei** [comment]
I checked the path. its already exists. I can share my Google Colab laptop. 
We double checked it on local machine and here is my screenshot:

![image](https://user-images.githubusercontent.com/32301411/210982221-f453d83a-fbd3-49fe-9b50-6c7f7b55102f.png)

I think this folder (`./images`) should be created at runtime. because it's not a part of your dataset directory and I saw some directories and images are being generated at runtime. so there might be a problem in previous lines of code; there is no significant error for this. 

I can share my google colab notebook (if you send me an email) and I can send my package versions if its needed.

tnx
