### ISSUE TITLE
Output-smpl-3\\smplmesh error

### ISSUE THREAD

**Issue by WilliamH07** [zju3dv/EasyMocap#254]
Hello, I have a problem with the monocular demo using this command :  `python apps/demo/mocap.py ${data} --work internet`  that I found here : https://chingswy.github.io/easymocap-public-doc/quickstart/quickstart.html  it gives me this error (the dataset is the example files for this command) : 

`(mocap) C:\Users\miste\Desktop\MOCAP\EasyMocap-master>python apps/demo/mocap.py C:\Users\miste\Desktop\1v1p --work internet
←[34m[run] python3 apps/calibration/create_blank_camera.py C:\Users\miste\Desktop\1v1p←[0m
[run] python3 apps/fit/fit.py --cfg_model config/model/smpl.yml --cfg_data config/data/multivideo.yml --cfg_exp config/fit/1v1p.yml --opt_data "args.path" "C:\Users\miste\Desktop\1v1p" "args.out" "C:\Users\miste\Desktop\1v1p\output-smpl-3d" "args.camera" "C:\Users\miste\Desktop\1v1p" --opt_exp "args.stages.joints.loss.k2d.weight" "100." "args.stages.joints.loss.k2d.args.norm" "gm"
Traceback (most recent call last):
  File "apps/demo/mocap.py", line 394, in <module>
    workflow(args.work, args)
  File "apps/demo/mocap.py", line 340, in workflow
    append_mocap_flags(path, output, cfg_data, cfg_model, cfg_exp, workflow.fit, args)
  File "apps/demo/mocap.py", line 277, in append_mocap_flags
    filenames = os.listdir(outdir)
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'C:\\Users\\miste\\Desktop\\1v1p\\output-smpl-3d\\smplmesh'`

My data folder contains : bodymodels, models and smplx. 
In bodymodels I have : manov1.2, SMPL_python_v.1.1.0 and smplhv1.2
In models : smpl_mean_params.npz, spin_checkpoint.pt, yolov4.weights
And in smplx it's the regular files with smpl, smplh and smplx.

I used this command line to install pytorch ... : `conda install pytorch==1.4.0 torchvision==0.5.0 cudatoolkit=10.1 -c pytorch`

But after that I still have the issue and I really don't know what to do 

BTW : I use python 3.7 and cuda 10.1 inside a conda environment on a RTX 2060 6GB

**Comment by WilliamH07** [comment]
Hi, my problem was the python installation that was wrong, after a lot of errors I decided to move on Ubuntu 22.0 and final it works, no more library errors or path errors. I recommend everyone to go on Ubuntu, my last 5 days was horrible on windows to try to make this thing working. Thanks a lot for your Amazing work ! The issue is now closed
