### ISSUE TITLE
Quick Start Demo error

### ISSUE THREAD

**Issue by samuelling2** [zju3dv/EasyMocap#257]
I tried to run the quick start demo for motion capture 
`(easymocap) C:\Users\Samuel\mocap\EasyMocap>python apps/demo/mocap.py 0_input\sample --work lightstage-dense-smplh --subs_vis 01 --ranges 0 800 1`

and it has error:

`[run] python apps/fit/triangulate1p.py --cfg_data config/recon/mv1p.yml --opt_data args.path 0_input\sample args.out 0_input\sample\output-keypoints3d args.subs_vis "['01']" args.ranges 0,800,1 --cfg_exp config/recon/triangulator-mv1p-total-mobilestage-studio.yml --opt_exp  args.debug False
[Config] merge from parent file: config/recon/triangulator-mv1p-total.yml
-> [Loading config/recon/mv1p.yml]:   6.0ms
Traceback (most recent call last):
  File "C:\Users\Samuel\mocap\EasyMocap\apps\fit\triangulate1p.py", line 95, in <module>
    dataset = load_object(cfg_data.module, cfg_data.args)
  File "c:\users\samuel\mocap\easymocap\easymocap\config\baseconfig.py", line 65, in load_object
    module = importlib.import_module(module_path)
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\users\samuel\mocap\easymocap\easymocap\datasets\base.py", line 7, in <module>
    from easymocap.dataset.config import coco17tobody25
  File "c:\users\samuel\mocap\easymocap\easymocap\dataset\__init__.py", line 11, in <module>
    from .mv1pmf_mirror import MV1PMF_Mirror
  File "c:\users\samuel\mocap\easymocap\easymocap\dataset\mv1pmf_mirror.py", line 14, in <module>
    from .mirror import calc_mirror_transform, flipSMPLParams, mirrorPoint3D, flipPoint2D, mirror_Rh
  File "c:\users\samuel\mocap\easymocap\easymocap\dataset\mirror.py", line 18, in <module>
    FLIP_SMPL_VERTICES = np.loadtxt(join(os.path.dirname(__file__), 'smpl_vert_sym.txt'), dtype=np.int)
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'. Did you mean: 'inf'?
[run] python -m easymocap.visualize.ffmpeg_wrapper 0_input\sample\output-keypoints3d/match --fps 50
[ffmpeg] No images in folder 0_input\sample\output-keypoints3d/match
[run] python apps/fit/fit.py --cfg_model config/model/smplh.yml --cfg_data config/data/mv1p.yml --cfg_exp config/fit/mv1p3dhand-new.yml --opt_data "args.path" "0_input\sample" "args.out" "0_input\sample\output-smpl-3d" "args.subs_vis" "['01']" "args.camera" "0_input\sample" "args.ranges" "0,800,1"
Traceback (most recent call last):
  File "C:\Users\Samuel\mocap\EasyMocap\apps\fit\fit.py", line 6, in <module>
    from easymocap.dataset.config import CONFIG
  File "c:\users\samuel\mocap\easymocap\easymocap\dataset\__init__.py", line 11, in <module>
    from .mv1pmf_mirror import MV1PMF_Mirror
  File "c:\users\samuel\mocap\easymocap\easymocap\dataset\mv1pmf_mirror.py", line 14, in <module>
    from .mirror import calc_mirror_transform, flipSMPLParams, mirrorPoint3D, flipPoint2D, mirror_Rh
  File "c:\users\samuel\mocap\easymocap\easymocap\dataset\mirror.py", line 18, in <module>
    FLIP_SMPL_VERTICES = np.loadtxt(join(os.path.dirname(__file__), 'smpl_vert_sym.txt'), dtype=np.int)
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'. Did you mean: 'inf'?
Traceback (most recent call last):
  File "C:\Users\Samuel\mocap\EasyMocap\apps\demo\mocap.py", line 394, in <module>
    workflow(args.work, args)
  File "C:\Users\Samuel\mocap\EasyMocap\apps\demo\mocap.py", line 340, in workflow
    append_mocap_flags(path, output, cfg_data, cfg_model, cfg_exp, workflow.fit, args)
  File "C:\Users\Samuel\mocap\EasyMocap\apps\demo\mocap.py", line 277, in append_mocap_flags
    filenames = os.listdir(outdir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '0_input\\sample\\output-smpl-3d\\smplmesh'`
![image](https://user-images.githubusercontent.com/116366411/212539252-b74e13e8-c07d-44ef-b858-0d564b985eb6.png)

How do i fix this?

**Comment by chingswy** [comment]
Seems like your numpy version is too old.

**Comment by samuelling2** [comment]
I just updated my numpy version but i still get the same issue when running the demo code
![image](https://user-images.githubusercontent.com/116366411/212562034-a2d5c50f-21ba-482a-9f96-3b0560c7ea4b.png)

**Comment by chingswy** [comment]
<img width="772" alt="图片" src="https://user-images.githubusercontent.com/22812405/212640983-5b5fab86-2983-459a-ba65-e188aa200594.png">

Can you run this command in python?

**Comment by chingswy** [comment]
<img width="772" alt="图片" src="https://user-images.githubusercontent.com/22812405/212640983-5b5fab86-2983-459a-ba65-e188aa200594.png">

Can you run this command in python?

**Comment by samuelling2** [comment]
> <img alt="图片" width="772" src="https://user-images.githubusercontent.com/22812405/212640983-5b5fab86-2983-459a-ba65-e188aa200594.png">
> 
> Can you run this command in python?

I just updated and installed my numpy to 1.23 version. and it shows this result so I'm guessing it works right.
![image](https://user-images.githubusercontent.com/116366411/212672896-d3733de0-82f3-4979-969b-c1172b44e3d7.png)


but when i run the code again, it shows
![image](https://user-images.githubusercontent.com/116366411/212672793-7aec7c8e-e236-4c88-ab3b-bf7c04404904.png)

**Comment by miguelmartin75** [comment]
numpy 1.24 seems to have removed np.int - I also ran into this issue with 1.24. I instead downgraded, as @samuelling2 did, to 1.23 (`pip install --upgrade numpy==1.23`) and the demo worked.

**Comment by chingswy** [comment]
Thanks @miguelmartin75 !

**Comment by samuelling2** [comment]
my numpy verison has been downgraded to 1.23
![image](https://user-images.githubusercontent.com/116366411/217564995-a2eb5483-2524-4c41-82d4-0a35f0f0d19b.png)

However, i still encounter this issue:

![image](https://user-images.githubusercontent.com/116366411/217565222-4531d2d3-fd9e-4bff-ad4f-9b75eb9d08c1.png)
