### ISSUE TITLE
some problems about Finetune the Chessboard Detection .

### ISSUE THREAD

**Issue by LRuid** [zju3dv/EasyMocap#275]
(l_easymocap) lrd@rtx3090-Super-Server:~/data/lrd/easymocap_filer/EasyMocap$ python apps/annotation/annot_calib.py /home/lrd/data/lrd/easymocap_filer/intri_data --mode chessboard --pattern 5,3 --annot chessboard

  \  Demo code for annotation:
   \ - Input : /home/lrd/data/lrd/easymocap_filer/intri_data
   \-      => "01", "02"
   \-      => chessboard

\ >>> label point 0
- Load data from /home/lrd/data/lrd/easymocap_filer/intri_data
- Try to find image names...
  -> find 30 images
- Try to find annot names...
  -> find 30 annots

Traceback (most recent call last):
  File "/data/lrd/easymocap_filer/EasyMocap/apps/annotation/annot_calib.py", line 163, in <module>
    annot_example(args.path, args)
  File "/data/lrd/easymocap_filer/EasyMocap/apps/annotation/annot_calib.py", line 153, in annot_example
    annotator.run()
  File "/data/lrd/easymocap_filer/EasyMocap/easymocap/annotator/basic_annotator.py", line 241, in run
    img = func(img, **self.param)
  File "/data/lrd/easymocap_filer/EasyMocap/apps/annotation/annot_calib.py", line 103, in vis
    if k2d[i][2] > 0 and k2d[j][2] > 0:
IndexError: index 15 is out of bounds for axis 0 with size 15

i have many images using extract_video.py and annot_calib.py . i use these images ,but it not work, What should I do?

**Comment by LRuid** [comment]
it work .      `apps/annotation/annot_calib.py`  . line 27
 `lines, lines_color = get_lines_chessboard((9,6))`  to modify 
 `lines, lines_color = get_lines_chessboard(args.pattern)`

**Comment by chingswy** [comment]
Thanks @LRuid , I will update it.
