### ISSUE TITLE
pyglet.gl.ContextException: Unable to share contexts.

### ISSUE THREAD

**Issue by henrenzhender** [zju3dv/EasyMocap#308]
(easymocap) E:\MOCAP\EasyMocap>python apps/demo/mv1p.py 0_input/project --out 1_output/project --vis_det --vis_repro --undis --sub_vis 1 2 3 4 --vis_smpl --end 650

  Demo code for multiple views and one person:

    - Input : 0_input/project => 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23
    - Output: 1_output/project
    - Body  : smpl=>neutral, body25

loading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 650/650 [00:03<00:00, 163.92it/s]
e:\mocap\easymocap\easymocap\pyfitting\lbfgs.py:264: UserWarning: This overload of add_ is deprecated:
        add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
        add_(Tensor other, *, Number alpha) (Triggered internally at  ..\torch\csrc\utils\python_arg_parser.cpp:1025.)
  p.data.add_(step_size, update[offset:offset + numel].view_as(p.data))
-> [Optimize global RT  ]:   4.2s
-> [Optimize 3D Pose/650 frames]:  25.6s
-> [Optimize 2D Pose/650 frames]:   4.4s
render:   0%|▏                                                                                                               | 1/650 [00:03<38:15,  3.54s/it]
Traceback (most recent call last):
  File "E:\MOCAP\EasyMocap\apps\demo\mv1p.py", line 117, in <module>
    mv1pmf_smpl(dataset, args)
  File "E:\MOCAP\EasyMocap\apps\demo\mv1p.py", line 88, in mv1pmf_smpl
    dataset.vis_smpl(vertices=vertices[0], faces=body_model.faces, images=images, nf=nf, sub_vis=args.sub_vis, add_back=True)
  File "e:\mocap\easymocap\easymocap\dataset\mv1pmf.py", line 47, in vis_smpl
    self.writer.vis_smpl(render_data, images, cameras, outname, add_back=add_back)
  File "e:\mocap\easymocap\easymocap\mytools\writer.py", line 73, in vis_smpl
    render = Renderer(height=1024, width=1024, faces=None)
  File "e:\mocap\easymocap\easymocap\visualize\renderer.py", line 85, in __init__
    self.renderer = pyrender.OffscreenRenderer(height, width)
  File "G:\Anaconda\envs\easymocap\lib\site-packages\pyrender\offscreen.py", line 31, in __init__
    self._create()
  File "G:\Anaconda\envs\easymocap\lib\site-packages\pyrender\offscreen.py", line 149, in _create
    self._platform.init_context()
  File "G:\Anaconda\envs\easymocap\lib\site-packages\pyrender\platforms\pyglet_platform.py", line 50, in init_context
    self._window = pyglet.window.Window(config=conf, visible=False,
  File "G:\Anaconda\envs\easymocap\lib\site-packages\pyglet\window\win32\__init__.py", line 104, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "G:\Anaconda\envs\easymocap\lib\site-packages\pyglet\window\__init__.py", line 578, in __init__
    self._create()
  File "G:\Anaconda\envs\easymocap\lib\site-packages\pyglet\window\win32\__init__.py", line 258, in _create
    self.context.attach(self.canvas)
  File "G:\Anaconda\envs\easymocap\lib\site-packages\pyglet\gl\win32.py", line 255, in attach
    super(Win32ARBContext, self).attach(canvas)
  File "G:\Anaconda\envs\easymocap\lib\site-packages\pyglet\gl\win32.py", line 202, in attach
    raise gl.ContextException('Unable to share contexts.')
pyglet.gl.ContextException: Unable to share contexts.

**Comment by chingswy** [comment]
https://chingswy.github.io/easymocap-public-doc/install/install_vis3d.html#install-pyrender
