### ISSUE TITLE
No module named 'myeasymocap.backbone.pare'

### ISSUE THREAD

**Issue by Xdex2** [zju3dv/EasyMocap#336]
Hello

After updating to the new version and running this command `emc --data config/datasets/svimage.yml --exp config/1v1p/hrnet_pare_finetune.yml --root .\data\examples\internet-rotate\ --ranges 0 500 1 --subs 23EfsN7vEOA+003170+003670`

I get this error

```
Traceback (most recent call last):
  File "C:\Users\{user}\source\repos\new-motion\Scripts\emc-script.py", line 33, in <module>
    sys.exit(load_entry_point('easymocap', 'console_scripts', 'emc')())
  File "c:\users\{user}\source\repos\new-motion\easymocap\apps\mocap\run.py", line 92, in main_entrypoint
    model = load_object(cfg_exp.module, cfg_exp.args)
  File "c:\users\{user}\source\repos\new-motion\easymocap\easymocap\config\baseconfig.py", line 67, in load_object
    obj = getattr(module, name)(**extra_args, **module_args)
  File "c:\users\{user}\source\repos\new-motion\easymocap\myeasymocap\stages\basestage.py", line 46, in __init__
    model = load_object(val['module'], val['args'])
  File "c:\users\{user}\source\repos\new-motion\easymocap\easymocap\config\baseconfig.py", line 65, in load_object
    module = importlib.import_module(module_path)
  File "C:\Users\{user}\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'myeasymocap.backbone.pare'    
```

Full log

```
Found 1 subjects in .\data\examples\internet-rotate\/images

emc --data config/datasets/svimage.yml --exp config/1v1p/hrnet_pare_finetune.yml --root .\data\examples\internet-rotate\ --ranges 0 500 1 --subs 23EfsN7vEOA+003170+003670
Found 1 subjects in .\data\examples\internet-rotate\/images
  -> Found 500 images in 23EfsN7vEOA+003170+003670.
  -> Min length: 500
[SVDataset] sub .\data\examples\internet-rotate\images\23EfsN7vEOA+003170+003670\000000.jpg shape (1080, 1920, 3)
[SVDataset] No camera info, use default camera
[SVDataset] Read shape (1080, 1920, 3) from image .\data\examples\internet-rotate\images\23EfsN7vEOA+003170+003670\000000.jpg
[SVDataset] Set a fix focal length 1296.0
 [Dataset] SVDataset
    root  : .\data\examples\internet-rotate\
    subs  : ['23EfsN7vEOA+003170+003670']
    ranges: [0, 500, 1]

[MultiStage] writing the results to output/sv1p
[MultiStage] loading module detect
[YoloWithTrack] Not given ckpt, use default yolov5
Using cache found in C:\Users\{user}/.cache\torch\hub\ultralytics_yolov5_master
requirements: C:\Users\{user}\.cache\torch\hub\requirements.txt not found, check failed.
YOLOv5  2023-5-4 Python-3.10.0 torch-2.0.1+cpu CPU

Fusing layers...
YOLOv5m summary: 290 layers, 21172173 parameters, 0 gradients
Adding AutoShape...
[MultiStage] loading module keypoints2d
[MultiStage] loading module vis2d
[MultiStage] loading module infer
Traceback (most recent call last):
  File "C:\Users\{user}\source\repos\new-motion\Scripts\emc-script.py", line 33, in <module>
    sys.exit(load_entry_point('easymocap', 'console_scripts', 'emc')())
  File "c:\users\{user}\source\repos\new-motion\easymocap\apps\mocap\run.py", line 92, in main_entrypoint
    model = load_object(cfg_exp.module, cfg_exp.args)
  File "c:\users\{user}\source\repos\new-motion\easymocap\easymocap\config\baseconfig.py", line 67, in load_object
    obj = getattr(module, name)(**extra_args, **module_args)
  File "c:\users\{user}\source\repos\new-motion\easymocap\myeasymocap\stages\basestage.py", line 46, in __init__
    model = load_object(val['module'], val['args'])
  File "c:\users\{user}\source\repos\new-motion\easymocap\easymocap\config\baseconfig.py", line 65, in load_object
    module = importlib.import_module(module_path)
  File "C:\Users\{user}\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'myeasymocap.backbone.pare'    
```

Did i miss something? I am trying to run the monocular demo from [here](https://chingswy.github.io/easymocap-public-doc/develop/03_fitsmpl_monocular.html)

**Comment by chingswy** [comment]
Fix it.
