### ISSUE TITLE
run mv1p.py demo, a exception happen "pyglet.gl.ContextException: Unable to share contexts.”

### ISSUE THREAD

**Issue by CHDTevior** [zju3dv/EasyMocap#347]
Hello, when I created my own multi-camera single-captured data set, when I ran the mv1p.py demo,

`python apps/demo/mv1p.py 0_input/project --out 1_output/project --vis_det --vis_repro --undis --sub_vis 1 2 3 4 5 --vis_smpl`

 it appeared:
render:   0%|▎                                                                                                                                                                                         | 1/600 [00:01<14:17,  1.43s/it] 
Traceback (most recent call last):
  File "F:\EasyMocap\EasyMocap\apps\demo\mv1p.py", line 117, in <module>
    mv1pmf_smpl(dataset, args)
  File "F:\EasyMocap\EasyMocap\apps\demo\mv1p.py", line 88, in mv1pmf_smpl
    dataset.vis_smpl(vertices=vertices[0], faces=body_model.faces, images=images, nf=nf, sub_vis=args.sub_vis, add_back=True)
  File "f:\easymocap\easymocap\easymocap\dataset\mv1pmf.py", line 47, in vis_smpl
    self.writer.vis_smpl(render_data, images, cameras, outname, add_back=add_back)
  File "f:\easymocap\easymocap\easymocap\mytools\writer.py", line 73, in vis_smpl
    render = Renderer(height=1024, width=1024, faces=None)
  File "f:\easymocap\easymocap\easymocap\visualize\renderer.py", line 85, in __init__
    self.renderer = pyrender.OffscreenRenderer(height, width)
  File "E:\ANACONDA\envs\easymocap\lib\site-packages\pyrender\offscreen.py", line 31, in __init__
    self._create()
  File "E:\ANACONDA\envs\easymocap\lib\site-packages\pyrender\offscreen.py", line 149, in _create
    self._platform.init_context()
  File "E:\ANACONDA\envs\easymocap\lib\site-packages\pyrender\platforms\pyglet_platform.py", line 50, in init_context
    self._window = pyglet.window.Window(config=conf, visible=False,
  File "E:\ANACONDA\envs\easymocap\lib\site-packages\pyglet\window\win32\__init__.py", line 104, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "E:\ANACONDA\envs\easymocap\lib\site-packages\pyglet\window\__init__.py", line 578, in __init__
    self._create()
  File "E:\ANACONDA\envs\easymocap\lib\site-packages\pyglet\window\win32\__init__.py", line 258, in _create
    self.context.attach(self.canvas)
  File "E:\ANACONDA\envs\easymocap\lib\site-packages\pyglet\gl\win32.py", line 255, in attach
    super(Win32ARBContext, self).attach(canvas)
  File "E:\ANACONDA\envs\easymocap\lib\site-packages\pyglet\gl\win32.py", line 202, in attach
    raise gl.ContextException('Unable to share contexts.')
pyglet.gl.ContextException: Unable to share contexts.

**Comment by chingswy** [comment]
Please check [here](https://chingswy.github.io/easymocap-public-doc/quickstart/debug_faq.html)
