### ISSUE TITLE
Error on gmm = pickle.load (f, encoding='latin1')

### ISSUE THREAD

**Issue by raflitp** [zju3dv/EasyMocap#418]
Hello @chingswy sorry to bother you with another issue and thank you for your great work and your team !!

I need help with this error that I got recently when I tried to ran yml from emc --cfg config/mvmp/body/ballet_2person.yml

Traceback (most recent call last):
  File "d:\easymocap\myeasymocap\stages\basestage.py", line 120, in at_final
    output = model(**inputs)
  File "d:\easymocap\myeasymocap\stages\basestage.py", line 155, in __call__
    output = stage(**inputs)
  File "d:\easymocap\myeasymocap\operations\optimizer.py", line 158, in __call__
    closure = make_closure(optimizer, model, params, infos_used, self.loss, device)
  File "d:\easymocap\myeasymocap\operations\optimizer.py", line 57, in make_closure
    loss_func[key] = load_object(val['module'], val['args'])
  File "d:\easymocap\easymocap\config\baseconfig.py", line 67, in load_object
    obj = getattr(module, name)(**extra_args, **module_args)
  File "d:\easymocap\easymocap\multistage\gmm.py", line 47, in __init__
    data = create_prior_from_cmu(num_gaussians)
  File "d:\easymocap\easymocap\multistage\gmm.py", line 13, in create_prior_from_cmu
    gmm = pickle.load(f, encoding='latin1')
EOFError: Ran out of input

I tried to solve it myself but I got no clue on how to solve it. I hope you can help me !! Thank You !!

**Comment by earthath** [comment]
Hi, I'm also had this error. how did you solve it?

**Comment by raflitp** [comment]
> Hi, I'm also had this error. how did you solve it?

Hi, I checked the gmm.py it seems to be calling the gmm_08.pkl file. Since the file can be opened, you might want to check the content of the file. If the file is empty then you might want to insert the content of the file or replace the file with the original one from the repository.

**Comment by MeiYouN** [comment]
> > 嗨，我也遇到了这个错误。您是怎么解决的？
> 
> 嗨，我检查了它似乎正在调用 gmm_08.pkl 文件 gmm.py。由于文件可以打开，因此您可能需要检查文件的内容。如果文件为空，则可能需要插入文件的内容或将文件替换为存储库中的原始文件。

I have also encountered this problem, and I have re downloaded the gmm_08. pkl file and replaced it, but it still reports an error. How did you operate it?
