### ISSUE TITLE
colab demo error: "RuntimeError: cublas runtime error"

### ISSUE THREAD

**Issue by xyyeah** [zju3dv/EasyMocap#80]
Hi~ Thanks for the exciting work~ When I run the colab script locally (Ubuntu20+cu111+A100, Pytorch1.8+python3.8), the following error occurred when I tested `PYOPENGAL_PLATFORM=osmesa python apps/demo/mv1p.py ../easy_mocap_data/ --out ../easy_mocap_data/output/smpl --vis_det --vis_repro --undis --sub_vis 1 7 13 19 --vis_smpl`:

````
Traceback (most recent call last):
  File "apps/demo/mv1p.py", line 117, in <module>
    mv1pmf_smpl(dataset, args)
  File "apps/demo/mv1p.py", line 69, in mv1pmf_smpl
    params = smpl_from_keypoints3d2d(body_model, kp3ds, keypoints2d, bboxes,
  File "~/EasyMocap/easymocap/pipeline/basic.py", line 64, in smpl_from_keypoints3d2d
    params_shape = optimizeShape(body_model, params_init, kp3ds,
  File "~/EasyMocap/easymocap/pyfitting/optimize_simple.py", line 71, in optimizeShape
    final_loss = fitting.run_fitting(optimizer, closure, opt_params)
  File "~/EasyMocap/easymocap/pyfitting/optimize.py", line 38, in run_fitting
    loss = optimizer.step(closure)
  File "~/EasyMocap/easymocap/pyfitting/lbfgs.py", line 307, in step
    orig_loss = closure()
  File "~/EasyMocap/easymocap/pyfitting/optimize_simple.py", line 46, in closure
    keypoints3d = body_model(return_verts=False, return_tensor=True, only_shape=True, **body_params)
  File "~.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "~/EasyMocap/easymocap/smplmodel/body_model.py", line 336, in forward
    rot = batch_rodrigues(Rh)
  File "~/EasyMocap/easymocap/smplmodel/lbs.py", line 310, in batch_rodrigues
    rot_mat = ident + sin * K + (1 - cos) * torch.bmm(K, K)
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:368
````

Any ideas about this error? Thanks~

**Comment by chingswy** [comment]
Have you fix it?

**Comment by xyyeah** [comment]
I cannot reproduce it again, maybe i got some params wrong, thanks for your reply.
