### ISSUE TITLE
ValueError: Cannot load file containing pickled data when allow_pickle=False

### ISSUE THREAD

**Issue by CGMikeG** [zju3dv/EasyMocap#83]
(easymocap) M:\GITHUB\EASYMOCAP>python apps/demo/1v1p_mirror.py zju-m-demo/ --out zju-m-demo-output/ --vis_smpl --video

  Demo code for single view and one person with mirror:

    - Input : zju-m-demo/: [backflip, dance, kaluli]
    - Output: zju-m-demo-output/
    - Body  : smpl => neutral, body25

-> [Loading smpl, neutral]:   3.6s
-> [Loading SPIN        ]: 390.0ms
Traceback (most recent call last):
  File "apps/demo/1v1p_mirror.py", line 153, in <module>
    device=body_model.device)
  File "C:\ProgramData\Miniconda3\envs\easymocap\lib\site-packages\easymocap\estimator\SPIN\spin_api.py", line 178, in __init__
    model = hmr(SMPL_MEAN_PARAMS).to(device)
  File "C:\ProgramData\Miniconda3\envs\easymocap\lib\site-packages\easymocap\estimator\SPIN\models.py", line 175, in hmr
    model = HMR(Bottleneck, [3, 4, 6, 3],  smpl_mean_params, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\easymocap\lib\site-packages\easymocap\estimator\SPIN\models.py", line 102, in __init__
    mean_params = np.load(smpl_mean_params)
  File "C:\ProgramData\Miniconda3\envs\easymocap\lib\site-packages\numpy\lib\npyio.py", line 445, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False

**Comment by chingswy** [comment]
Maybe some errors about your environment.

**Comment by Kirstihly** [comment]
I resolved the problem by double-checking the `smpl_mean_params.npz` downloaded from `wget -c http://visiondata.cis.upenn.edu/spin/data.tar.gz`. It should be 1.3kB.
