### ISSUE TITLE
RuntimeError: The size of tensor a (42) must match the size of tensor b (0) at non-singleton dimension 1

### ISSUE THREAD

**Issue by neilgogogo** [zju3dv/EasyMocap#90]
Demo code for multiple views and one person:

    - Input : /data/CMU_pose/171026_pose2_sample2 => 00, 01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
    - Output: /data/CMU_pose/171026_pose2_sample2/output/smplx
    - Body  : smplx=>male, body25

triangulation: 100%|##############################################################################| 297/297 [44:23<00:00,  8.97s/it]
dump: 100%|#####################################################################################| 297/297 [00:00<00:00, 4726.59it/s]
loading: 100%|####################################################################################| 297/297 [00:03<00:00, 83.65it/s]
/EasyMocap/easymocap/pyfitting/lbfgs.py:264: UserWarning: This overload of add_ is deprecated:
        add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
        add_(Tensor other, *, Number alpha) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:1025.)
  p.data.add_(step_size, update[offset:offset + numel].view_as(p.data))
-> [Optimize global RT  ]:   3.7s
-> [Optimize 3D Pose/297 frames]:  19.6s
Traceback (most recent call last):
  File "apps/demo/mv1p.py", line 117, in <module>
    mv1pmf_smpl(dataset, args)
  File "apps/demo/mv1p.py", line 71, in mv1pmf_smpl
    weight_shape=weight_shape, weight_pose=weight_pose)
  File "/EasyMocap/easymocap/pipeline/basic.py", line 77, in smpl_from_keypoints3d2d
    params = multi_stage_optimize(body_model, params, kp3ds, kp2ds, bboxes, Pall, weight_pose, cfg)
  File "/EasyMocap/easymocap/pipeline/basic.py", line 29, in multi_stage_optimize
    params = optimizePose3D(body_model, params, kp3ds, weight=weight, cfg=cfg)
  File "/EasyMocap/easymocap/pyfitting/optimize_simple.py", line 301, in optimizePose3D
    params = _optimizeSMPL(body_model, params, prepare_funcs, postprocess_funcs, loss_funcs, weight_loss=weight, cfg=cfg)
  File "/EasyMocap/easymocap/pyfitting/optimize_simple.py", line 246, in _optimizeSMPL
    final_loss = fitting.run_fitting(optimizer, closure, opt_params)
  File "/EasyMocap/easymocap/pyfitting/optimize.py", line 38, in run_fitting
    loss = optimizer.step(closure)
  File "/usr/local/lib/python3.6/dist-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/EasyMocap/easymocap/pyfitting/lbfgs.py", line 307, in step
    orig_loss = closure()
  File "/EasyMocap/easymocap/pyfitting/optimize_simple.py", line 231, in closure
    loss_dict = {key:func(kpts_est=kpts_est, **new_params) for key, func in loss_funcs.items()}
  File "/EasyMocap/easymocap/pyfitting/optimize_simple.py", line 231, in <dictcomp>
    loss_dict = {key:func(kpts_est=kpts_est, **new_params) for key, func in loss_funcs.items()}
  File "/EasyMocap/easymocap/pyfitting/lossfactory.py", line 63, in hand
    diff_square = (kpts_est[:, 25:25+42, :3] - self.keypoints3d[:, 25:25+42, :3])*self.conf[:, 25:25+42]
RuntimeError: The size of tensor a (42) must match the size of tensor b (0) at non-singleton dimension 1

Thank you very much for your awesome work
I also met this error when I tried to run the code with smplx. 
I deleted the keypoints3d folder and rerun the code, but it did not work? How can I solve this?

**Comment by chingswy** [comment]
Hello, it seems that you specify wrong `--body_type`. If you use smplx, you should use `--body_type bodyhandface`

**Comment by mertmerci** [comment]
Hi @neilgogogo, I am facing with the same issue and could not figure out how to solve it. In addition @chingswy , when I include `--body bodyhandface` to the command, I receive the following error: 
`EasyMocap-master % python3 apps/demo/mv1p.py ${data} --out ${data}/output/smplx --vis_det --vis_repro --undis --body bodyhandface --model smplx --gender male --vis_smpl

  Demo code for multiple views and one person:

    - Input : seq => 1, 2, 3
    - Output: seq/output/smplx
    - Body  : smplx=>male, bodyhandface

loading:   0%|                                                                                                                                                                         | 0/4756 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "apps/demo/mv1p.py", line 117, in <module>
    mv1pmf_smpl(dataset, args)
  File "apps/demo/mv1p.py", line 59, in mv1pmf_smpl
    images, annots = dataset[nf]
  File "/Users/user/Desktop/KTH_RE/EasyMocap-master/easymocap/dataset/mv1pmf.py", line 72, in __getitem__
    images, annots_all = super().__getitem__(index)
  File "/Users/user/Desktop/KTH_RE/EasyMocap-master/easymocap/dataset/base.py", line 482, in __getitem__
    annot = read_annot(annname, self.kpts_type)
  File "/Users/user/Desktop/KTH_RE/EasyMocap-master/easymocap/mytools/file_utils.py", line 81, in read_annot
    data[i]['keypoints'] = np.vstack([data[i][key] for key in ['keypoints', 'handl2d', 'handr2d', 'face2d']])
  File "/Users/user/Desktop/KTH_RE/EasyMocap-master/easymocap/mytools/file_utils.py", line 81, in <listcomp>
    data[i]['keypoints'] = np.vstack([data[i][key] for key in ['keypoints', 'handl2d', 'handr2d', 'face2d']])
KeyError: 'handl2d'`

Do you have any suggestions?

**Comment by chingswy** [comment]
Make sure that you have detected the hand keypoints.

**Comment by mertmerci** [comment]
Hi @chingswy, thank you for your prompt response. When I selected `--body body25`, I get a similar error as above: 
`python3 apps/demo/mv1p.py ${data} --out ${data}/output/smplx --vis_det --vis_repro --undis --body body25 --model smplx --gender male --vis_smpl

  Demo code for multiple views and one person:

    - Input : seq => 1, 2, 3
    - Output: seq/output/smplx
    - Body  : smplx=>male, body25

loading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4756/4756 [00:06<00:00, 695.93it/s]
-> [Optimize global RT  ]:  51.0s
-> [Optimize 3D Pose/4756 frames]: 352.4s
Traceback (most recent call last):
  File "apps/demo/mv1p.py", line 117, in <module>
    mv1pmf_smpl(dataset, args)
  File "apps/demo/mv1p.py", line 69, in mv1pmf_smpl
    params = smpl_from_keypoints3d2d(body_model, kp3ds, keypoints2d, bboxes, 
  File "/Users/user/Desktop/KTH_RE/EasyMocap-master/easymocap/pipeline/basic.py", line 77, in smpl_from_keypoints3d2d
    params = multi_stage_optimize(body_model, params, kp3ds, kp2ds, bboxes, Pall, weight_pose, cfg)
  File "/Users/user/Desktop/KTH_RE/EasyMocap-master/easymocap/pipeline/basic.py", line 29, in multi_stage_optimize
    params = optimizePose3D(body_model, params, kp3ds, weight=weight, cfg=cfg)
  File "/Users/user/Desktop/KTH_RE/EasyMocap-master/easymocap/pyfitting/optimize_simple.py", line 301, in optimizePose3D
    params = _optimizeSMPL(body_model, params, prepare_funcs, postprocess_funcs, loss_funcs, weight_loss=weight, cfg=cfg)
  File "/Users/user/Desktop/KTH_RE/EasyMocap-master/easymocap/pyfitting/optimize_simple.py", line 246, in _optimizeSMPL
    final_loss = fitting.run_fitting(optimizer, closure, opt_params)
  File "/Users/user/Desktop/KTH_RE/EasyMocap-master/easymocap/pyfitting/optimize.py", line 38, in run_fitting
    loss = optimizer.step(closure)
  File "/Users/user/Desktop/KTH_RE/EasyMocap-master/easymocap/pyfitting/lbfgs.py", line 307, in step
    orig_loss = closure()
  File "/Users/user/Desktop/KTH_RE/EasyMocap-master/easymocap/pyfitting/optimize_simple.py", line 231, in closure
    loss_dict = {key:func(kpts_est=kpts_est, **new_params) for key, func in loss_funcs.items()}
  File "/Users/user/Desktop/KTH_RE/EasyMocap-master/easymocap/pyfitting/optimize_simple.py", line 231, in <dictcomp>
    loss_dict = {key:func(kpts_est=kpts_est, **new_params) for key, func in loss_funcs.items()}
  File "/Users/user/Desktop/KTH_RE/EasyMocap-master/easymocap/pyfitting/lossfactory.py", line 63, in hand
    diff_square = (kpts_est[:, 25:25+42, :3] - self.keypoints3d[:, 25:25+42, :3])*self.conf[:, 25:25+42]
RuntimeError: The size of tensor a (42) must match the size of tensor b (0) at non-singleton dimension 1
`

Do you have any suggestions for me to solve it?

**Comment by chingswy** [comment]
If you use `body15`, you can just optimize SMPL model instead of SMPLX model.

**Comment by mertmerci** [comment]
I do not face with any problems with SMPL model however I want to generate a more detailed model using SMPLX. I managed to make SMPLX work with another recording using `body25` but I cannot right now due to the error I mentioned above.

**Comment by chingswy** [comment]
It's not implement yet when using `SMPLX` + `body25`, I just implement `SMPLX` + `bodyhandface` or `SMPL` + `body25`.

**Comment by mertmerci** [comment]
Thanks @chingswy anyway, I just opened a new issue for this problem #105, since it is not solved.
