### ISSUE TITLE
运行示例demo出了问题

### ISSUE THREAD

**Issue by ShamLich** [zju3dv/EasyMocap#96]
python scripts/preprocess/extract_video.py datasets --handface这一句可以顺利的运行
python apps/demo/mv1p.py datasets  --out datasets/output/smpl --vis_det --vis_repro --undis --sub_vis 1 --vis_smpl运行这一句会出现两个问题
1是生成的keypoints3d下的json文件中所有值都为0
2是最终报错如下

  Demo code for multiple views and one person:

    - Input : E:/Users/ShamLich/Documents/GitHub/EasyMocap/datasets => 1
    - Output: E:/Users/ShamLich/Documents/GitHub/EasyMocap/datasets/output/smpl
    - Body  : smpl=>neutral, body25

triangulation: 100%|█████████████████████████████████████████████████████████████████| 800/800 [00:50<00:00, 15.76it/s]
dump: 100%|████████████████████████████████████████████████████████████████████████| 800/800 [00:00<00:00, 2912.78it/s]
loading: 100%|█████████████████████████████████████████████████████████████████████| 800/800 [00:00<00:00, 2659.10it/s]
-> [Optimize global RT  ]:   0.0ms
Traceback (most recent call last):
  File "apps/demo/mv1p.py", line 116, in <module>
    mv1pmf_smpl(dataset, args)
  File "apps/demo/mv1p.py", line 69, in mv1pmf_smpl
    params = smpl_from_keypoints3d2d(body_model, kp3ds, keypoints2d, bboxes,
  File "e:\users\shamlich\documents\github\easymocap\easymocap\pipeline\basic.py", line 77, in smpl_from_keypoints3d2d
    params = multi_stage_optimize(body_model, params, kp3ds, kp2ds, bboxes, Pall, weight_pose, cfg)
  File "e:\users\shamlich\documents\github\easymocap\easymocap\pipeline\basic.py", line 18, in multi_stage_optimize
    params = optimizePose3D(body_model, params, kp3ds, weight=weight, cfg=cfg)
  File "e:\users\shamlich\documents\github\easymocap\easymocap\pyfitting\optimize_simple.py", line 301, in optimizePose3D
    params = _optimizeSMPL(body_model, params, prepare_funcs, postprocess_funcs, loss_funcs, weight_loss=weight, cfg=cfg)
  File "e:\users\shamlich\documents\github\easymocap\easymocap\pyfitting\optimize_simple.py", line 246, in _optimizeSMPL
    final_loss = fitting.run_fitting(optimizer, closure, opt_params)
  File "e:\users\shamlich\documents\github\easymocap\easymocap\pyfitting\optimize.py", line 38, in run_fitting
    loss = optimizer.step(closure)
  File "e:\users\shamlich\documents\github\easymocap\easymocap\pyfitting\lbfgs.py", line 307, in step
    orig_loss = closure()
  File "e:\users\shamlich\documents\github\easymocap\easymocap\pyfitting\optimize_simple.py", line 227, in closure
    new_params = func(new_params)
  File "e:\users\shamlich\documents\github\easymocap\easymocap\pyfitting\optimize_simple.py", line 121, in interp_func
    params[key][nf] = interp(params[key][left], params[key][right], 1-weight, key=key)
IndexError: index 800 is out of bounds for dimension 0 with size 800

**Comment by Langwenchong** [comment]
@ShamLich 你好我现在也面临这个问题请麻烦问一下是哪里配置有问题吗

**Comment by outbreak-sen** [comment]
> [@ShamLich](https://github.com/ShamLich) 你好我现在也面临这个问题请麻烦问一下是哪里配置有问题吗

这个我也遇到了，发现是三角测量出现问题，一般如果二维关键点找到准的话，那就是相机参数有问题，我发现这个相机外参的旋转是和一般定义不同的，要变换一下，具体可以用apps/calibration/vis_camera_by_open3d.py看一下你的相机z轴是不是朝着世界系的
